[tool.poetry]
name = "buymeatdaraz"
version = "0.1.0"
description = ""
authors = ["Shahriar-Ferdoush <1805101@ugrad.cse.buet.ac.bd>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
